### ISSUE TITLE
`npm run dev:oidc` broken

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-frontend#1034] opened 2024-10-15 09:20 UTC
It looks like `npm run dev:oidc` no longer serves frontend with OIDC enabled:

![Screenshot_2024-10-15_12-19-35](https://github.com/user-attachments/assets/7b733a57-fd5f-4083-a8b9-a25b54b848e4)

Possibly affected by 9236c61b0ce6035fbaf53f257e5f228b52874a3a

**Comment by alxndrsn** [comment] 2024-10-15 09:23
Temporary fix:

```diff
--- a/main.nginx.conf
+++ b/main.nginx.conf
@@ -96,7 +96,7 @@ http {
 
     location = /client-config.json {
       include ./common-headers.nginx.conf;
-      return 200 "{}";
+      return 200 "{ \"oidcEnabled\": \"true\" }";
     }
 
     location / {
```

**Comment by matthew-white** [comment] 2024-10-15 15:57
Hmm I'm actually having trouble reproducing this. `npm run dev:oidc` is working on my machine and shows the OIDC login page.

> Possibly affected by 9236c61b0ce6035fbaf53f257e5f228b52874a3a

My intention at least was to keep `npm run dev:oidc` working when I made that change. You can see that `VUE_APP_OIDC_ENABLED` is still referenced in src/config.js. src/config.js specifies the defaults for the client config, which are then merged with the response from /client-config.json (which is `{}` in dev).

---

Could it be that the environment variable isn't getting passed through for some reason? Could you try `console.log(process.env.VUE_APP_OIDC_ENABLED)` ?

**Comment by matthew-white** [comment] 2024-10-15 16:38
I've actually been having the thought that now that Frontend requests /client-config.json, we might be able to take a more flexible approach than what we currently do with `npm run dev:oidc`. I'm thinking that instead of running `npm run dev:oidc`, you could run the normal `npm run dev`, but modify a local client-config.json file to specify `{ "oidcEnabled": true }`. The local client-config.json is intended to work sort of like an .env file, where options are passed in, but don't show up in version control. Let me know if you think that approach might be useful: #1038.

**Closed** 2024-10-16 05:50 UTC
